name: Mirror to GitLab

on:
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Mirror GitHub â†’ GitLab
        run: |
          git clone https://github.com/MasterKia/PersianBlocker.git
          cd PersianBlocker
          git remote set-url origin https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.com/Parsast/PersianBlocker.git
          git push -u origin main

